# Generated by Django 3.2.5 on 2021-09-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='goal',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='project',
            name='not_for_profit',
            field=models.BooleanField(default=False),
        ),
    ]
